# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'matrix_morph_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Morph_Ui(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(535, 324)
        Form.setMinimumSize(QtCore.QSize(535, 324))
        Form.setMaximumSize(QtCore.QSize(535, 480))
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(2, 0, 531, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 5, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 2, 1, 1)
        self.label2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label2.setObjectName("label2")
        self.gridLayout.addWidget(self.label2, 2, 2, 1, 1)
        self.mtx = QtWidgets.QTableWidget(self.gridLayoutWidget)
        self.mtx.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.mtx.setRowCount(3)
        self.mtx.setColumnCount(3)
        self.mtx.setObjectName("mtx")
        self.mtx.horizontalHeader().setVisible(False)
        self.mtx.horizontalHeader().setDefaultSectionSize(80)
        self.mtx.horizontalHeader().setHighlightSections(False)
        self.mtx.horizontalHeader().setMinimumSectionSize(30)
        self.mtx.verticalHeader().setVisible(False)
        self.mtx.verticalHeader().setDefaultSectionSize(60)
        self.mtx.verticalHeader().setHighlightSections(False)
        self.gridLayout.addWidget(self.mtx, 0, 0, 9, 2)
        self.lnHor = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lnHor.setObjectName("lnHor")
        self.gridLayout.addWidget(self.lnHor, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 8, 2, 1, 1)
        self.label1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label1.setObjectName("label1")
        self.gridLayout.addWidget(self.label1, 0, 2, 1, 1)
        self.lnVer = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lnVer.setObjectName("lnVer")
        self.gridLayout.addWidget(self.lnVer, 3, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label3.setObjectName("label3")
        self.horizontalLayout.addWidget(self.label3)
        self.lnX = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lnX.setEnabled(True)
        self.lnX.setObjectName("lnX")
        self.horizontalLayout.addWidget(self.lnX)
        self.label4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label4.setObjectName("label4")
        self.horizontalLayout.addWidget(self.label4)
        self.lnY = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lnY.setEnabled(False)
        self.lnY.setObjectName("lnY")
        self.horizontalLayout.addWidget(self.lnY)
        self.gridLayout.addLayout(self.horizontalLayout, 6, 2, 1, 1)
        self.confirm = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.confirm.setObjectName("confirm")
        self.gridLayout.addWidget(self.confirm, 7, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 3)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Структурирующий элемент"))
        self.label.setText(_translate("Form", "Координаты чего-то там"))
        self.label2.setText(_translate("Form", "По вертикали:"))
        self.label1.setText(_translate("Form", "По горизонтали:"))
        self.label3.setText(_translate("Form", "x:"))
        self.lnX.setPlaceholderText(_translate("Form", "1"))
        self.label4.setText(_translate("Form", "y:"))
        self.lnY.setPlaceholderText(_translate("Form", "1"))
        self.confirm.setText(_translate("Form", "Применить"))

